-- Upgrade an early CollabCanvas schema to the Phase 1 foundation schema.
-- This migration is intentionally data-preserving and can also run after the
-- regular foundation migrations.

create extension if not exists pgcrypto with schema extensions;

do $$
begin
  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'public' and t.typname = 'board_visibility'
  ) then
    create type public.board_visibility as enum (
      'private',
      'organization',
      'public_readonly',
      'public_editable'
    );
  end if;

  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'public' and t.typname = 'board_role'
  ) then
    create type public.board_role as enum ('owner', 'editor', 'viewer');
  end if;
end
$$;

do $$
begin
  if exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'public'
      and t.typname = 'board_visibility'
      and t.typtype = 'e'
  ) then
    alter type public.board_visibility add value if not exists 'private';
    alter type public.board_visibility add value if not exists 'organization';
    alter type public.board_visibility add value if not exists 'public_readonly';
    alter type public.board_visibility add value if not exists 'public_editable';
  end if;

  if exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'public'
      and t.typname = 'board_role'
      and t.typtype = 'e'
  ) then
    alter type public.board_role add value if not exists 'owner';
    alter type public.board_role add value if not exists 'editor';
    alter type public.board_role add value if not exists 'viewer';
  end if;
end
$$;

-- Enum additions must commit before the new labels can be used by later DML.
begin;

alter table public.profiles
  add column if not exists updated_at timestamptz not null default now();

alter table public.boards
  add column if not exists share_token_hash text,
  add column if not exists last_activity_at timestamptz not null default now();

alter table public.board_members
  add column if not exists invited_by uuid references public.profiles(id) on delete set null;

alter table public.board_invitations
  add column if not exists token_hash text,
  add column if not exists revoked_at timestamptz,
  add column if not exists invited_by uuid references public.profiles(id) on delete restrict;

-- Convert legacy invitation tokens to one-way hashes before removing plaintext.
do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'board_invitations'
      and column_name = 'token'
  ) then
    execute $sql$
      update public.board_invitations
      set token_hash = encode(extensions.digest(token, 'sha256'), 'hex')
      where token_hash is null and token is not null
    $sql$;
  end if;
end
$$;

update public.board_invitations invitation
set invited_by = board.owner_id
from public.boards board
where board.id = invitation.board_id
  and invitation.invited_by is null;

do $$
begin
  if exists (
    select 1 from public.board_invitations
    where token_hash is null or invited_by is null
  ) then
    raise exception
      'Cannot upgrade invitations: an invitation is missing a token or its board owner';
  end if;
end
$$;

alter table public.board_invitations
  alter column token_hash set not null,
  alter column invited_by set not null;

create unique index if not exists board_invitations_token_hash_key
  on public.board_invitations(token_hash);

alter table public.board_invitations drop column if exists token;

create table if not exists public.board_recent_access (
  user_id uuid not null references public.profiles(id) on delete cascade,
  board_id uuid not null references public.boards(id) on delete cascade,
  last_opened_at timestamptz not null default now(),
  primary key (user_id, board_id)
);

create table if not exists public.board_activity (
  id bigint generated by default as identity primary key,
  board_id uuid not null references public.boards(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete set null,
  action text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.board_snapshots (
  id uuid primary key default gen_random_uuid(),
  board_id uuid not null references public.boards(id) on delete cascade,
  object_key text not null,
  sequence_number bigint not null,
  byte_size bigint not null check (byte_size >= 0),
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (board_id, sequence_number)
);

create table if not exists public.asset_records (
  id uuid primary key default gen_random_uuid(),
  board_id uuid not null references public.boards(id) on delete cascade,
  uploaded_by uuid references public.profiles(id) on delete set null,
  object_key text not null unique,
  file_name text not null,
  content_type text not null,
  byte_size bigint not null check (byte_size >= 0),
  created_at timestamptz not null default now()
);

create index if not exists boards_owner_id_idx
  on public.boards(owner_id);
create index if not exists boards_last_activity_at_idx
  on public.boards(last_activity_at desc);
create index if not exists board_members_user_id_idx
  on public.board_members(user_id);
create index if not exists board_invitations_board_id_idx
  on public.board_invitations(board_id);
create index if not exists board_invitations_email_idx
  on public.board_invitations(lower(email));
create index if not exists board_recent_access_user_opened_idx
  on public.board_recent_access(user_id, last_opened_at desc);
create index if not exists board_activity_board_created_idx
  on public.board_activity(board_id, created_at desc);
create index if not exists board_snapshots_board_sequence_idx
  on public.board_snapshots(board_id, sequence_number desc);
create index if not exists asset_records_board_created_idx
  on public.asset_records(board_id, created_at desc);

-- Remove legacy policies before installing the complete Phase 1 policy set.
do $$
declare
  policy_record record;
begin
  for policy_record in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename = any (array[
        'profiles',
        'boards',
        'board_members',
        'board_invitations',
        'board_recent_access',
        'board_activity',
        'board_snapshots',
        'asset_records'
      ])
  loop
    execute format(
      'drop policy if exists %I on %I.%I',
      policy_record.policyname,
      policy_record.schemaname,
      policy_record.tablename
    );
  end loop;
end
$$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name, avatar_url)
  values (
    new.id,
    coalesce(
      nullif(new.raw_user_meta_data ->> 'display_name', ''),
      nullif(new.raw_user_meta_data ->> 'full_name', ''),
      split_part(coalesce(new.email, ''), '@', 1),
      'User'
    ),
    nullif(new.raw_user_meta_data ->> 'avatar_url', '')
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

create or replace function public.add_owner_membership()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.board_members (board_id, user_id, role, invited_by)
  values (new.id, new.owner_id, 'owner', new.owner_id)
  on conflict (board_id, user_id) do nothing;

  return new;
end;
$$;

create or replace function public.is_board_owner(
  target_board_id uuid,
  target_user_id uuid default auth.uid()
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.boards board
    where board.id = target_board_id
      and board.owner_id = target_user_id
  );
$$;

create or replace function public.board_role_for(
  target_board_id uuid,
  target_user_id uuid default auth.uid()
)
returns public.board_role
language sql
stable
security definer
set search_path = ''
as $$
  select member.role::text::public.board_role
  from public.board_members member
  where member.board_id = target_board_id
    and member.user_id = target_user_id
  limit 1;
$$;

create or replace function public.can_view_board(
  target_board_id uuid,
  target_user_id uuid default auth.uid()
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.boards board
    where board.id = target_board_id
      and (
        board.owner_id = target_user_id
        or exists (
          select 1
          from public.board_members member
          where member.board_id = board.id
            and member.user_id = target_user_id
        )
        or board.visibility::text in ('public_readonly', 'public_editable')
      )
  );
$$;

create or replace function public.shares_board_with(
  target_user_id uuid,
  requesting_user_id uuid default auth.uid()
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select target_user_id = requesting_user_id
    or exists (
      select 1
      from public.board_members mine
      join public.board_members theirs on theirs.board_id = mine.board_id
      where mine.user_id = requesting_user_id
        and theirs.user_id = target_user_id
    );
$$;

create or replace function public.accept_board_invitation(invitation_token text)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  invitation public.board_invitations%rowtype;
  normalized_email text;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  normalized_email := lower(coalesce(auth.jwt() ->> 'email', ''));

  select *
  into invitation
  from public.board_invitations
  where token_hash = encode(
    extensions.digest(invitation_token, 'sha256'),
    'hex'
  )
    and accepted_at is null
    and revoked_at is null
    and expires_at > now()
  for update;

  if invitation.id is null then
    raise exception 'Invitation is invalid or expired';
  end if;

  if lower(invitation.email) <> normalized_email then
    raise exception 'Invitation email does not match the signed-in user';
  end if;

  insert into public.board_members (board_id, user_id, role, invited_by)
  values (
    invitation.board_id,
    auth.uid(),
    invitation.role,
    invitation.invited_by
  )
  on conflict (board_id, user_id) do update
  set role = case
    when public.board_members.role::text = 'owner'
      then public.board_members.role
    else excluded.role
  end;

  update public.board_invitations
  set accepted_at = now()
  where id = invitation.id;

  return invitation.board_id;
end;
$$;

create or replace function public.reject_board_invitation(invitation_token text)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  invitation public.board_invitations%rowtype;
  normalized_email text;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  normalized_email := lower(coalesce(auth.jwt() ->> 'email', ''));

  select *
  into invitation
  from public.board_invitations
  where token_hash = encode(
    extensions.digest(invitation_token, 'sha256'),
    'hex'
  )
    and accepted_at is null
    and revoked_at is null
    and expires_at > now()
  for update;

  if invitation.id is null then
    raise exception 'Invitation is invalid or expired';
  end if;

  if lower(invitation.email) <> normalized_email then
    raise exception 'Invitation email does not match the signed-in user';
  end if;

  update public.board_invitations
  set revoked_at = now()
  where id = invitation.id;

  return invitation.board_id;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists boards_set_updated_at on public.boards;
create trigger boards_set_updated_at
before update on public.boards
for each row execute function public.set_updated_at();

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

drop trigger if exists boards_add_owner_membership on public.boards;
create trigger boards_add_owner_membership
after insert on public.boards
for each row execute function public.add_owner_membership();

insert into public.board_members (board_id, user_id, role, invited_by)
select board.id, board.owner_id, 'owner', board.owner_id
from public.boards board
on conflict (board_id, user_id) do nothing;

alter table public.profiles enable row level security;
alter table public.boards enable row level security;
alter table public.board_members enable row level security;
alter table public.board_invitations enable row level security;
alter table public.board_recent_access enable row level security;
alter table public.board_activity enable row level security;
alter table public.board_snapshots enable row level security;
alter table public.asset_records enable row level security;

create policy profiles_select_shared
on public.profiles for select
using (public.shares_board_with(id));

create policy profiles_update_self
on public.profiles for update
using (id = auth.uid())
with check (id = auth.uid());

create policy boards_select_accessible
on public.boards for select
using (public.can_view_board(id));

create policy boards_insert_owner
on public.boards for insert
with check (owner_id = auth.uid());

create policy boards_update_owner_or_editor
on public.boards for update
using (
  owner_id = auth.uid()
  or public.board_role_for(id)::text = 'editor'
)
with check (
  owner_id = auth.uid()
  or public.board_role_for(id)::text = 'editor'
);

create policy boards_delete_owner
on public.boards for delete
using (owner_id = auth.uid());

create policy board_members_select_accessible
on public.board_members for select
using (public.can_view_board(board_id));

create policy board_members_insert_owner
on public.board_members for insert
with check (public.is_board_owner(board_id));

create policy board_members_update_owner
on public.board_members for update
using (public.is_board_owner(board_id))
with check (public.is_board_owner(board_id));

create policy board_members_delete_owner_or_self
on public.board_members for delete
using (
  public.is_board_owner(board_id)
  or (
    user_id = auth.uid()
    and role::text <> 'owner'
  )
);

create policy board_invitations_select_owner_or_invitee
on public.board_invitations for select
using (
  public.is_board_owner(board_id)
  or lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
);

create policy board_invitations_insert_owner
on public.board_invitations for insert
with check (
  public.is_board_owner(board_id)
  and invited_by = auth.uid()
);

create policy board_invitations_update_owner
on public.board_invitations for update
using (public.is_board_owner(board_id))
with check (public.is_board_owner(board_id));

create policy board_invitations_delete_owner
on public.board_invitations for delete
using (public.is_board_owner(board_id));

create policy board_recent_access_select_self
on public.board_recent_access for select
using (user_id = auth.uid());

create policy board_recent_access_insert_self
on public.board_recent_access for insert
with check (
  user_id = auth.uid()
  and public.can_view_board(board_id)
);

create policy board_recent_access_update_self
on public.board_recent_access for update
using (user_id = auth.uid())
with check (
  user_id = auth.uid()
  and public.can_view_board(board_id)
);

create policy board_recent_access_delete_self
on public.board_recent_access for delete
using (user_id = auth.uid());

create policy board_activity_select_accessible
on public.board_activity for select
using (public.can_view_board(board_id));

create policy board_activity_insert_member
on public.board_activity for insert
with check (
  user_id = auth.uid()
  and public.board_role_for(board_id)::text in ('owner', 'editor')
);

create policy board_snapshots_select_accessible
on public.board_snapshots for select
using (public.can_view_board(board_id));

create policy asset_records_select_accessible
on public.asset_records for select
using (public.can_view_board(board_id));

revoke all on function public.is_board_owner(uuid, uuid) from public;
revoke all on function public.board_role_for(uuid, uuid) from public;
revoke all on function public.can_view_board(uuid, uuid) from public;
revoke all on function public.shares_board_with(uuid, uuid) from public;
revoke all on function public.accept_board_invitation(text) from public;
revoke all on function public.reject_board_invitation(text) from public;

grant execute on function public.is_board_owner(uuid, uuid) to authenticated;
grant execute on function public.board_role_for(uuid, uuid) to authenticated;
grant execute on function public.can_view_board(uuid, uuid) to anon, authenticated;
grant execute on function public.shares_board_with(uuid, uuid) to authenticated;
grant execute on function public.accept_board_invitation(text) to authenticated;
grant execute on function public.reject_board_invitation(text) to authenticated;

notify pgrst, 'reload schema';

commit;
